# ==================================================
#  MangoWC - (2026)
#  Mango Monitor Rules
# ==================================================

# Virtual Machine monitor rule (forces 1080p60 on virtual display)
monitorrule=name:Virtual-1,width:1920,height:1080,refresh:60,x:0,y:0,scale:1.0,vrr:0

# Default monitor rule (matches any output, auto-detects native resolution and refresh rate)
# Format: monitorrule=name:<pattern>,width:<w>,height:<h>,refresh:<hz>,x:<x>,y:<y>,scale:<s>,vrr:<0|1>
monitorrule=name:.*,scale:1.0,vrr:0
