# ==================================================
#  MangoWC - (2026)
#  Noctalia Theme Palette for Mango
# ==================================================

shadowscolor = 0x000000ff
rootcolor = 0x171214ff
bordercolor = 0x9c8d92ff
focuscolor = 0xffafd7ff
maximizescreencolor = 0xdfbdccff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xf3ba9bff
globalcolor = 0x772958ff
overlaycolor = 0x58404bff
