# ==================================================
#  MangoWC - (2026)
#  Mango Window Rules
# ==================================================

# Floating kitty window (spawned via SUPER+CTRL+Return)
windowrule=isfloating:1,width:900,height:600,title:floating-kitty

# Picture-in-picture
windowrule=isfloating:1,title:Picture-in-Picture

# Noctalia Settings - centered, floating, and 75% of screen
windowrule=isfloating:1,width:0.75,height:0.75,appid:dev.noctalia.Noctalia

# Launch apps on fixed tags
windowrule=tags:2,appid:google-chrome
windowrule=tags:3,appid:discord
windowrule=tags:3,appid:discord-canary
windowrule=tags:9,appid:com.obsproject.Studio
