# ==================================================
#  MangoWC - (2026)
#  Mango Tag (Workspace) Configuration
# ==================================================

# Available layouts: tile, scroller, grid, deck, monocle, center_tile,
#                    vertical_tile, right_tile, vertical_scroller,
#                    vertical_grid, vertical_deck, dwindle, fair,
#                    vertical_fair, tgmix
# Format: tagrule=id:<tag_id>,monitor_name:<monitor>,layout_name:<layout>

# Default layout for tags 1-9
tagrule=id:1,monitor_name:.*,layout_name:dwindle
tagrule=id:2,monitor_name:.*,layout_name:dwindle
tagrule=id:3,monitor_name:.*,layout_name:dwindle
tagrule=id:4,monitor_name:.*,layout_name:dwindle
tagrule=id:5,monitor_name:.*,layout_name:dwindle
tagrule=id:6,monitor_name:.*,layout_name:dwindle
tagrule=id:7,monitor_name:.*,layout_name:dwindle
tagrule=id:8,monitor_name:.*,layout_name:dwindle
tagrule=id:9,monitor_name:.*,layout_name:dwindle
