hl.env("GTK_THEME", "Adwaita:dark")
hl.env("GTK_ICON_THEME", "Adwaita")
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("EDITOR", "nvim")
hl.env("VISUAL", "neovide")
hl.env("HYPRBTW", "0.5.3")
hl.env("NOCTALIA_CONFIG_HOME", os.getenv("HOME") .. "/.config/hypr")
hl.env("NOCTALIA_STATE_HOME", os.getenv("HOME") .. "/.local/state/hypr")
